apiVersion: v1
kind: Service
metadata:
   name: init-some-service-1
spec:
   ports:
   - protocol: TCP
     port: 80
     targetPort: 9377
---
apiVersion: v1
kind: Service
metadata:
   name: init-some-service-2
spec:
   ports:
   - protocol: TCP
     port: 80
     targetPort: 9378

