apiVersion: batch/v1
kind: Job
metadata:
   name: pi
spec:
   completions: 5 # total number of pods
   parallelism: 3 #create parallel pods
   backoffLimit: 4 #Failed Pods associated with the Job are recreated by the JobController with an exponential back-off delay (10s,20s,40s…) capped backofflimit(Default Value is: 6 minutes)
   ttlSecondsAfterFinished: 100
   template:
      spec:
         containers:
         - name: pi
           image: perl
           command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(200)"]
         restartPolicy: Never