apiVersion: v1
kind: PersistentVolume
metadata:
   name: mypv0001
spec:
   capacity:
      storage: 2Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: standard-storage-class
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /tmp
      server: 172.17.0.2