apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller1
spec:
  replicas: 3
  selector:
    app: rc1
    environment: dev
  template:
    metadata:
      name: rc1
      labels:
        app: rc1
        environment: dev
    spec:
      containers:
      - name: rc1
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']