apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   shareProcessNamespace: true
   containers:
   - name: nginx
     image: nginx
   - name: shell
     image: busybox
     securityContext:
        capabilities:
           add:
           - SYS_PTRACE
     stdin: true
     tty: true
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx1
spec:
   containers:
   - name: nginx1
     image: nginx
     stdin: true
     tty: true
   - name: shell1
     image: busybox
     securityContext:
        capabilities:
           add:
           - SYS_PTRACE
     stdin: true
     tty: true
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx2
spec:
   shareProcessNamespace: true
   containers:
   - name: nginx2
     image: nginx2
   - name: shell2
     image: busybox
     stdin: true
     tty: true