apiVersion: v1
kind: Service
metadata:
   name: nginx
   labels:
      app: nginx
spec:
   ports:
   - port: 80
     name: web
   clusterIP: None
   selector:
      app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: stetefulsettest
spec:
   selector:
      matchLabels:
         app: nginx #has to match with spec.template.metadata.lables
   serviceName: "nginx"
   replicas: 1
   template:
      metadata:
         labels:
            app: nginx #has to matched spec.selector.matchlabels
      spec:
         terminationGracePeriodSeconds: 10
         containers:
         - name: nginx
           image: k8s.gcr.io/nginx-slim:0.8
           ports:
           - containerPort: 80
             name: web
           volumeMounts:
           - name: stetefulsettestclaim1
             mountPath: /usr/share/nginx/html
   volumeClaimTemplates:
   - metadata:
       name: stetefulsettestclaim1
     spec:
         accessModes: 
            - ReadWriteOnce
         storageClassName: standard-storage-class
         resources:
             requests:
                storage: 1Gi