apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: pizza-container
        image: linuxacademycontent/pizza-service:1.14.6
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: pizza-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: pizza
  ports:
  - protocol: TCP
    port: 80
    nodePort: 80 

      