apiVersion: v1
kind: Pod
metadata: 
   name: high-priority-pod7
spec:
   containers:
   - name: high-priority-container
     image: ubuntu
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo hello; sleep 10; done"]
     resources:
        requests:
           cpu: 300m
           memory: 300Mi
   priorityClassName: high  
              