apiVersion: v1
kind: LimitRange
metadata:
   name: limit-mem-cpu-per-container
spec:
   limits:
   - max:
         cpu: 800m
         memory: 800Mi
     min: 
         cpu: 100m
         memory: 100Mi
     default:
         cpu: 100m
         memory: 100Mi
     type: Container
     