apiVersion: v1
kind: List
items:
   - apiVersion: v1
     kind: ResourceQuota
     metadata:
        name: objects
     spec:
        hard:
           cpu: 1000m
           memory: 1000Mi
           pods: 3
           configmaps: "10"
           persistentvolumeclaims: "4"
           replicationcontrollers: "20"
           secrets: "10"
           services: "10"
           services.loadbalancers: "2"
                    
   - apiVersion: v1
     kind: ResourceQuota
     metadata:
        name: pods-medium
     spec:
        hard:
           cpu: 800m
           memory: 800Mi
           pods: 3
        scopeSelector:
           matchExpressions:
           - operator: In
             scopeName: PriorityClass
             values: ["medium"]
   
   - apiVersion: v1
     kind: ResourceQuota
     metadata:
        name: pods-low
     spec:
        hard:
           cpu: 600m
           memory: 600Mi
           pods: 3
        scopeSelector:
           matchExpressions:
           - operator: In
             scopeName: PriorityClass
             values: ["low"]                 
              
               