apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  myKey: myPassword
---
apiVersion: v1
kind: Pod
metadata:
  name: my-sceret-pod
spec:
  containers:
  - name: my-sceret-pod
    image: busybox
    command: ['sh', '-c', "echo hello, kube! && sleep 3600"]
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: myKey

