apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  volumes:
  - name: vol1
    emptyDir: {}
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - name: vol1
      mountPath: /data/redis