apiVersion: v1
kind: ConfigMap
metadata:
  name: am-server-conf
  labels:
    name: am-server-conf
  namespace: monitoring
data:
  alertmanager.yml: |-
  
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'sysdig-test'
      '
    receivers:
    - name: 'sysdig-test'
      webhook_configs:
    - url: 'https://webhook.site/d9f04786-802b-49a5-a3e0-4208ddd88f2d'