apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
      matchLabels:
        app: prometheus-server
  template:
    metadata:
      name: promethues-pod
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.2.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
              
            - name: prometheus-storage-volume
              mountPath: /prometheus/
              
            - name: am-prom-general-rules
              mountPath: /etc/prometheus/rules/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
            
        - name: am-prom-general-rules
          configMap:
            defaultMode: 420
            name: am-prom-general-rules

        - name: prometheus-storage-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: monitoring
  labels:
     app: alertmanager
spec:
   replicas: 1
   selector:
     matchLabels:
       app: alertmanager
   template:
      metadata:
         labels:
           app: alertmanager
      spec:
        containers:
         - name: alertmanager
           image: prom/alertmanager
           args:
             - "--config.file=/etc/alertmanager/alertmanager.yml"
             - '--storage.path=/alertmanager'
           volumeMounts:
              - name: am-server-conf
                mountPath: /etc/alertmanager/
              - name: alertmanager
                mountPath: /alertmanager
           ports:
           - containerPort: 9093
        volumes:
        - name: alertmanager
          emptyDir: {}
        - name: am-server-conf
          configMap:
            name: am-server-conf
---